"use strict";
let num = 25;
let str = "Hello, TypeScript!";
let bool = true;
let nullable = null;
let undef = undefined;
let anything = "I can be anything";
console.log("Number:", num);
console.log("String:", str);
console.log("Boolean:", bool);
console.log("Null:", nullable);
console.log("Undefined:", undef);
console.log("Any:", anything);
